### ISSUE TITLE
Registering new data on a running viewer

### ISSUE THREAD

**Issue by muffato** [blobtoolkit/viewer#18]
Hello,

I've got a viewer running with Docker
```
exec docker run -d --rm --name btk \
	-v /data/blobplots:/blobtoolkit/datasets -p 8000:8000 -p 80:8080 \
	-e VIEWER=true -e BTK_API_URL -e BTK_ORIGINS \
	genomehubs/blobtoolkit:latest
```
I'd like the viewer to notice when I add a new directory. i saw this in the log and I initially thought the viewer would pick up all new directories, but it seems to rather be the node server itself looking for javascript files, not data
```
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
```
At the moment, I plan to restart BTL whenever the data change. Any other suggestions ?

Matthieu

**Comment by rjchallis** [comment]
This had me confused for a moment as I thought the API would restart on data change when run in this way. There is no explicit monitoring of the data directory, but you can use the code-watching if you place the datasets directory inside the viewer code directory. This is how I have my dev environment set up for convenience so I overlooked the fact that it isn't a feature that translates into the default Docker setup.

Monitoring the data directory would be more elegant but for now hopefully moving the data directory will get you the behaviour that you want.

**Comment by muffato** [comment]
Nice trick 🤝 ! Yes it works.
I only had to increase `fs.inotify.max_user_watches` because the default value in OpenStack was 8K

**Comment by muffato** [comment]
Hello,

(cc-ing @gq1 who found the issue)
We're back to square 1 as `inotify` events are not propagated through the `/lustre` mount on OpenStack. Could there be an API endpoint, or a refresh button, or etc, for the viewer to reload the list of datasets available on disk ? (instead of having to restart the complete application)

Cheers,
Matthieu

**Comment by rjchallis** [comment]
I've created an API endpoint to reload the search index without a restart that hopefully solves this in [feature/reload_key](https://github.com/blobtoolkit/viewer/tree/feature/reload_key) So there will be no need for the datasets in the code directory hack. Just needs a `BTK_RELOAD_KEY` environment variable, then visiting search/reload/:key will trigger a reload of the search index.

e.g.
```
BTK_RELOAD_KEY=testkey npm start
```

```
curl -s http://localhost:8008/api/v1/search/reload/testkey

{"status":"updated"}
```

**Comment by gq1** [comment]
Thanks Richard. Can you please push a docker image for this? It will be easier for me to test on Kubernetes.

**Comment by muffato** [comment]
Thanks Richard !

**Comment by rjchallis** [comment]
I've pushed a container image to genomehubs/blobtoolkit:reload_key for you to try out.

**Comment by gq1** [comment]
Thanks Richard.

Got some errors when loading the front page:

(node:35) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'values' of undefined
    at search (/blobtoolkit/viewer/src/server/routes/search_routes.js:253:14)
    at /blobtoolkit/viewer/src/server/routes/search_routes.js:471:16
    at Layer.handle [as handle_request] (/blobtoolkit/viewer/node_modules/express/lib/router/layer.js:95:5)
    at next (/blobtoolkit/viewer/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/blobtoolkit/viewer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/blobtoolkit/viewer/node_modules/express/lib/router/layer.js:95:5)
    at /blobtoolkit/viewer/node_modules/express/lib/router/index.js:281:22
    at param (/blobtoolkit/viewer/node_modules/express/lib/router/index.js:354:14)
    at param (/blobtoolkit/viewer/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/blobtoolkit/viewer/node_modules/express/lib/router/index.js:410:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rjchallis** [comment]
I'd left some variable settings inside a conditional - have just updated the image so this should work more generally

**Comment by gq1** [comment]
Different error this time:

    251 const search = (term) => {
    252   if (term.match(/^all$/i)) return meta.filter((o) => o.latest == o.revision);
    253   if (!index.values[term]) return [];
    254   let arr = [];
    255   let ids = {};

(node:34) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'values' of undefined
    at search (/blobtoolkit/viewer/src/server/routes/search_routes.js:253:14)
    at /blobtoolkit/viewer/src/server/routes/search_routes.js:471:16
    at Layer.handle [as handle_request] (/blobtoolkit/viewer/node_modules/express/lib/router/layer.js:95:5)
    at next (/blobtoolkit/viewer/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/blobtoolkit/viewer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/blobtoolkit/viewer/node_modules/express/lib/router/layer.js:95:5)
    at /blobtoolkit/viewer/node_modules/express/lib/router/index.js:281:22
    at param (/blobtoolkit/viewer/node_modules/express/lib/router/index.js:354:14)
    at param (/blobtoolkit/viewer/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/blobtoolkit/viewer/node_modules/express/lib/router/index.js:410:3)
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by rjchallis** [comment]
Sorry - the new code didn't make it into the image last time. Should work now

**Comment by gq1** [comment]
Thanks Richard. The new image works and the API call also works.

**Comment by muffato** [comment]
Thank you very much @rjchallis ! I'll close the ticket, now
