### ISSUE TITLE
No dataset loading

### ISSUE THREAD

**Issue by pgonzale60** [blobtoolkit/viewer#2]
Hi Rich,

I launched the viewer by activating the blobtools2 conda environment and then `blobtools host hs_Omyriophila/`. I can see the dataset when I write "all" in the query field. I can even see the metadata details, but when I click on the dataset, it sends me to "http://localhost:8080/view/all/dataset/hs_Omyriophila/blob" and this webpage keeps loading dataset for minutes. This is my smallest dataset. Can you check whether my dataset works for you? If yes, than what logfile could I look to check what happens when I try to load the dataset? If no, how can it be solved?

[blob_hs_Omyriophila.tar.gz](https://github.com/blobtoolkit/viewer/files/3585055/blob_hs_Omyriophila.tar.gz)

Cheers,
Pablo

**Comment by rjchallis** [comment]
I had added code that didn't allow for an optional metadata value to be unset. The latest commit should have fixed this and I was able to load your dataset locally.

**Comment by pgonzale60** [comment]
I've removed my previous viewer directory and pulled a new copy of the repository (1e3d4ff). I still have the same issue. If you can load the dataset, then there is something wrong with my viewer or blobtools2 installation. All I see is that the dataset does not load after several hours and the only thing I see in the terminal is 
```
Starting BlobToolKit API on port 8000 (pid: 17015)
Starting BlobToolKit viewer on port 8080 (pid: 17036)
Visit http://localhost:8080 to use the interactive BlobToolKit Viewer.
```
  How can I trace my error?

**Comment by rjchallis** [comment]
This looks like it is happening because you are giving the path to the dataset directory instead of the path to the directory containing the dataset directory. The idea is that it will host all the datasets in a given parent directory, but this has proved to be somewhat counterintuitive. 

I've updated the BlobTools2 code to check and host the parent directory if necessary. You could either change your command to specify the parent directory, or run the latest BlobTools2 code. Hope this fixes the issue for you.

**Comment by pgonzale60** [comment]
I updated the code and now issue `./blobtools2/blobtools host .` from the directory where I have all my datasets, blobtools2 and viewer directories. Thanks for solving the issue!

**Comment by pgonzale60** [comment]
I also moved my taxdump to the same directory of blobtools2, as specified in the README.md. Maybe my issue arised because previously I had my taxdump directory in an unrelated directory. Maybe blobtools2 was trying to load it although it wasn't there. Thanks again for addressing this issue.
