### ISSUE TITLE
add coverage disrupt the viewer image loading. 

### ISSUE THREAD

**Issue by yizhouc** [blobtoolkit/viewer#21]
Hi, I am new to use blobtoolikt. I just start following the tutorial provided on the website. 
I am able to create the ASSEMBLY_NAME/blob and use a local instance to view the blob. When I add the busco data. it is fine. However, when I added the S_venezuelensis_HH1/DRR008460_cov.json (download as instructed). there is error message. however when try to use the viewer, I couldn't load the image anymore. 
The web page become blank.

**Comment by yizhouc** [comment]
There is typo. There is no error message when I added the --cov
~/blobtoolkit/blobtools2/blobtools add \
     --cov ~/BTK_TUTORIAL/FILES/S_venezuelensis_HH1/DRR008460_cov.json \
     ~/BTK_TUTORIAL/DATASETS/ASSEMBLY_NAME

**Comment by rjchallis** [comment]
Glad it seems to be working now. Just to clarify did you mean that you found a typo in the tutorial that I should fix, or was it in the command you had entered?

**Comment by yizhouc** [comment]
Thanks. It is a typo in my first message, where I missed the "no". in the sentence. Not in your tutorial. 
Here are some issues I have when I ran the tutorials, some maybe  due to my lacking experience in this area.
To install with conda, an extra run is needed for conda install r requirements.txt.

I am using OS ubuntu 18.04. I followed  the steps in the tutorial, 
1) to create the database is fine. I can use the viewer to load the scaffold statistic in the web browser. 
2) add the BUSSO is fine, I can use the viewer and load the BUSCO statistics in the web page along with snail graph.    
3) when I add -- cov, although there is no error message displayed in promot, the web page becomes blank.  I repeated it twice, the results are the same. following are the command I used.
~/blobtoolkit/blobtools2/blobtools add
--cov ~/BTK_TUTORIAL/FILES/S_venezuelensis_HH1/DRR008460_cov.json
~/BTK_TUTORIAL/DATASETS/ASSEMBLY_NAME
4) to add blast hit, the download ncbi.blastn.out, I got error  "gzip: stdin: not in gzip format"
curl https://blobtoolkit.genomehubs.org/download/ALIAS/S_v/S_venezuelensis_HH1/S_venezuelensis_HH1.blastn.nt.root.1.minus.6247.out.gz | gunzip -c > ASSEMBLY_NAME.ncbi.blastn.out

5) add the --hit for the diamond blatx.out file 
~/blobtoolkit/blobtools2/blobtools add \
    --hits ~/BTK_TUTORIAL/FILES/ASSEMBLY_NAME.diamond.blastx.out \
    --taxrule bestsumorder \
    --taxdump ~/databases/ncbi_taxdump \
    ~/BTK_TUTORIAL/DATASETS/ASSEMBLY_NAME  

Traceback (most recent call last):
  File "/home/yizhouc/blobtoolkit/blobtools2/lib/add.py", line 194, in <module>
    main()
  File "/home/yizhouc/blobtoolkit/blobtools2/lib/add.py", line 152, in main
    meta=meta
  File "/home/yizhouc/blobtoolkit/blobtools2/lib/hits.py", line 525, in parse
    int(kwargs["--hit-count"]),
  File "/home/yizhouc/blobtoolkit/blobtools2/lib/hits.py", line 154, in bin_hits
    windows = set_windows(meta, taxrule)
  File "/home/yizhouc/blobtoolkit/blobtools2/lib/hits.py", line 117, in set_windows
    if "stats_windows" in meta.settings:
AttributeError: settings
