### ISSUE TITLE
[v2.6.2] Viewing BLAST hits produces blank page

### ISSUE THREAD

**Issue by kubu4** [blobtoolkit/viewer#23]
When viewing the table of scaffolds, I click on a colored square under the "Categories" column (e.g. Square next to "Mollusca" under the `buscogenes phylum` sub-category). This loads a new page, but the page is entirely blank:

![image](https://user-images.githubusercontent.com/4514104/128219914-f3268848-7816-45cf-a620-50c71316767b.png)

**Comment by rjchallis** [comment]
I'm not able to reproduce this one - do you get any error messages in the browser javascript console?

**Comment by kubu4** [comment]
There are some errors in the console:

![image](https://user-images.githubusercontent.com/4514104/128864558-086f3050-b5dc-489a-8e57-bbbff1a2c39f.png)

**Comment by rjchallis** [comment]
Sorry this one fell off my radar. It was a problem with link generation so the plot could link out to NCBI/ENA. I've pushed a commit that should stop this error. To get the default linkouts you can set `BTK_USE_DEFAULT_LINKS=true`
