### ISSUE TITLE
blobtoolkit viewer: problems with npm install

### ISSUE THREAD

**Issue by gitcruz** [blobtoolkit/viewer#3]
Dear all,

After loading the required cluster modules in our cluster (module load gcc/6.3.0 mkl/11.3.3 PYTHON/3.6.0 CONDA/4.5.11_PYTHON3) I have followed the installation steps for blobtools2 (https://github.com/blobtoolkit/blobtools2). Then I tested all the commands (create,add...) they worked well with exception of host and view (logical, as they require installing the viewer).

The problems come when running "npm install". First it complained about Livpips versuo above 8.. so I try to solve this by running: 

conda install -c bioconda -y libvips

It worked but now I am having issues with the npm install and a bunch of errors:

_i_nfo sharp Detected globally-installed libvips v8.8.3
info sharp Building from source via node-gyp
basename: missing operand
Try `basename --help' for more information.
gyp: Call to 'PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips-cpp' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/devel/fcruz/.conda/envs/blobtoolkit/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 2.6.32-696.13.2.el6.Bull.128.x86_64
gyp ERR! command "/home/devel/fcruz/.conda/envs/blobtoolkit/bin/node" "/home/devel/fcruz/.conda/envs/blobtoolkit/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/devel/fcruz/bin/programs/viewer/node_modules/sharp
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

[then a bunch of warnings..]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.21.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above__

I have been looking into the corresponding lines at "node-gyp.js" but it's not clear what could be the cause. I also don't find the events.js in the folder. 

However, at the end of the log complains about "peer depedencies" and the platform (I am installing it in a Unix server, that should be fine...but fsevents wanted MacOS?)

4548 warn react-d3-axis@0.1.1 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
4549 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/nodemon/node_modules/fsevents):
4550 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
4551 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4551 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4551 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
4551 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4552 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
4553 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
4554 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4554 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4554 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
4554 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4555 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/chokidar/node_modules/fsevents):
4556 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
4557 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4557 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4557 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
4557 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4558 verbose stack Error: sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
4558 verbose stack Exit status 1
4558 verbose stack     at EventEmitter.<anonymous> (/home/devel/fcruz/.conda/envs/blobtoolkit/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
4558 verbose stack     at EventEmitter.emit (events.js:182:13)
4558 verbose stack     at ChildProcess.<anonymous> (/home/devel/fcruz/.conda/envs/blobtoolkit/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4558 verbose stack     at ChildProcess.emit (events.js:182:13)
4558 verbose stack     at maybeClose (internal/child_process.js:962:16)
4558 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
4559 verbose pkgid sharp@0.21.3
4560 verbose cwd /home/devel/fcruz/bin/programs/viewer
4561 verbose Linux 2.6.32-696.13.2.el6.Bull.128.x86_64
4562 verbose argv "/home/devel/fcruz/.conda/envs/blobtoolkit/bin/node" "/home/devel/fcruz/.conda/envs/blobtoolkit/bin/npm" "install"
4563 verbose node v10.13.0
4564 verbose npm  v6.4.1
4565 error code ELIFECYCLE
4566 error errno 1
4567 error sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
4567 error Exit status 1
4568 error Failed at the sharp@0.21.3 install script.
4568 error This is probably not a problem with npm. There is likely additional logging output above.
4569 verbose exit [ 1, true ]

Do you have any idea on how to solve this problem? any hints to make this work?

Thanks,
Fernando

**Comment by rjchallis** [comment]
Hi Fernando

Dealing with things that can be safely ignored first: 

* I've developed this on OS X and ubuntu - fsevents is a Mac-specific optional dependency that will generate a warning, but shouldn't cause any problems on other UNIX flavours.

* react-d3-axis just hadn't been updated when I last bumped the versions. It still works fine with React v16 even though it asks for v15

I remember having a couple of problems with sharp a while back but thought that the current versions were working well across most systems, but apparently not. Can you try a minimal install to see if you can get sharp working regardless of the specific versions in the viewer package.json?

Something like:

```
conda create -n sharp_test
conda activate sharp_test
conda install nodejs=10
mkdir -p sharp_test_dir && cd sharp_test_dir
npm init 
npm install --no-cache sharp
``` 

The npm install should fetch libvips automatically but if you are still getting errors, it may be that it just needs a different version. sharp@0.24.0 is the latest version on npm and uses libvips@8.9.0.

If you manage to get sharp installed, you could try again with the specific version used in the viewer (which uses libvips@8.7.0):

```
npm uninstall sharp
npm install --no-cache sharp@0.21.3
```

Let me know how you get on and hopefully it will become clearer how to solve this for you.

Cheers

Richard

**Comment by gitcruz** [comment]
Hi Richard,

I am getting the same exact result.

I tried to install libvips 8.9.0 but I can't find it at any repo. Using 8.8.3, I still get this after npm install:
> sharp@0.24.0 install /home/devel/fcruz/bin/programs/sharp_test_dir/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp Use with glibc 2.12 requires manual installation of libvips >= 8.9.0
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing......

I'm afraid I am not very savy with conda. tried to install the specific version as conda install libvips=8.9.0 but does not work...

Any other idea?

Thanks for your help,
Fernando

**Comment by rjchallis** [comment]
I think you need to try to avoid manually installing libvips if possible as that step shouldn't be necessary. Looking at the error message again

```
ERR! sharp Use with glibc 2.12 requires manual installation of libvips >= 8.9.0
```

that version of glibc is 10 years old. The [version of libvips](https://github.com/lovell/sharp-libvips/releases) that can be downloaded automatically needs at least glibc 1.17.

If you can't get this upgraded on your cluster, there are some newer (but still old) versions available on random conda channels. I managed to get 2.18 working in a stacked environment, putting it in the same env as node was causing errors:

```
(sharp_test) $ conda create sharp_sub
(sharp_test) $ conda activate --stack sharp_sub
(sharp_sub) $ conda install -c dan_blanchard glibc
(sharp_sub) $ ldd --version  # should be 2.18
(sharp_sub) $ npm install --no-cache sharp
```

This may work for you but I'm not sure as I ran the commands on a machine with glibc 2.27 as the default that I had to roll back.

Richard

**Comment by gitcruz** [comment]
Thanks Richard, 
I asked the cluster administrators about this. I am trying to fix it by upgrading glibc 2.19...but I did not manage yet.
I will keep you updated on this.
Thanks

**Comment by pgonzale60** [comment]
Hi Rich,

This is the error I get in when doing npm install.

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-darwin-x64.tar.gz
sh: prebuild-install: command not found
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/pg17/miniconda2/envs/blobtools2/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/pg17/miniconda2/envs/blobtools2/bin/node" "/Users/pg17/miniconda2/envs/blobtools2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pg17/Documents/Investigacion/chromEvoN/sw/btk/viewer/node_modules/sharp
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN react-d3-axis@0.1.2 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN blobtoolkit-viewer@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pg17/Documents/Investigacion/chromEvoN/sw/btk/viewer/false/_logs/2020-01-30T19_20_48_242Z-debug.log

Then I ran `npm install prebuild-install; rm -r node_modules/sharp/; npm install`
And this solved the issue. Maybe you want to add it to the recipe.

Cheers,
Pablo

**Comment by rjchallis** [comment]
Thanks Pablo, I've added rebuild-install to the dependencies so hopefully this will help.

I'm also putting all of BlobToolKit into a Docker so there will be a containerised version that should work anywhere docker can run. I'll link it from here once it is ready.

**Comment by rjchallis** [comment]
Adding the link to the [BlobToolKit Docker](https://github.com/blobtoolkit/blobtoolkit-docker)
