### ISSUE TITLE
Upload new dataset?

### ISSUE THREAD

**Issue by Andrew-N-Black** [blobtoolkit/viewer#7]
Hello,
I'd like to upload a blobdir from a local instance to make it public; is there a way to do this?
Thanks!
-Andrew

**Comment by rjchallis** [comment]
You can set up a public instance using the Viewer code if you want to handle hosting yourself. The process is very similar to running the viewer locally with a few different environment variables.

Alternatively if you'd like to add a dataset to the public viewer, there isn't a formal mechanism but this is certainly possible. Easiest if the raw data are already on or headed for ENA/NCBI as the various link outs will work. 

If you could let me know which option you meant, I can be more specific.

**Comment by black1414** [comment]
Our data isn't formatted for NCBI yet, but that is the route we will be going later this month. Therefore, we are looking to add a dataset to the public viewer

**Comment by rjchallis** [comment]
OK, that's great. Happy to help get this added. If you could you collect together the BlobDir and BLAST/BUSCO result files as in https://blobtoolkit.genomehubs.org/download/ALIAS/mSc/mSciVul1_1/ then we can make these available as downloads.

As it will soon be on NCBI, it will be useful to make sure the coverage field names match the SRA accessions and that all of the bio project/biosample information is in the metadata. I can help with this once you send the files if they need editing - changing individual meta entries is straightforward in blobtools2, but I've not yet added an option to quickly change field names if you have the coverage imported under different names.

I won't be able to do anything on this next week, but once you have the files ready, could you email blobtoolkit@genomehubs.org so we can arrange to transfer them.
