### ISSUE TITLE
CSV button not working

### ISSUE THREAD

**Issue by pgonzale60** [blobtoolkit/viewer#9]
Hi Rich,

I can't download the tables found at different part of Blobtoolkit. This I try by pressing the CSV buttons found in the [main page of the viewer](https://blobtoolkit.genomehubs.org/view/all#Datasets) and the [table view](https://blobtoolkit.genomehubs.org/view/all/dataset/AAAA02/table#Filters). 
I see the same behavior in local instances pulling the latest viewer version (_f5926d92ac6_).

Is there a simple way to export such tables from the interactive session?

Thanks,
Pablo

**Comment by rjchallis** [comment]
Hi Pablo

I'm unable to reproduce this issue - the csv download links seem to be working on both public and local instances in Chrome, Firefox and Safari. 

Do you have a pop up blocker? The buttons should trigger a file download from a temporary location, which the browser may interpret as a pop up window so you may need to add btk to a list of allowed sites?

Rich

**Comment by pgonzale60** [comment]
Hi Rich,

I confirm this wasn't a viewer issue. I only had to deactivate the pop-up blocker.

Thank you for figuring this out,
Pablo
